name: ci

on:
  push:
    branches:
      - "main"

env:
  APP_NAME: ichigrinova/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.APP_NAME }}:buildcache,mode=max
          push: true
          tags: ${{ env.APP_NAME }}:buildcache


      - name: Test app
        run: make app-test

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile.production
          tags: |
            ${{ APP_NAME }}:${{ steps.vars.outputs.tag }}
            ${{ APP_NAME }}:latest