name: ci

on:
  push:
    branches:
      - "main"

env:
  APP_NAME: ichigrinova/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.APP_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: echo "Tags [${{steps.meta.outputs.tags}}]"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          cache-from: type=registry,ref=${{ env.APP_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.APP_NAME }}:buildcache,mode=max
          tags: ${{ env.APP_NAME }}:buildcache


      - name: Test app
        run: make app-test

      - name: Push to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=registry,ref=${{ env.APP_NAME }}:buildcache
          tags: ${{ steps.meta.outputs.tags }}